# ECS CHANGE DETECTION PARAMETERS

# ECS SWITCHER PARAMETERS
ecs_switcher_default_process: test1

ecs_switcher:

  - name: test1
    pkg: ecs_switcher
    process: node1.launch

  - name: test2
    pkg: ecs_switcher
    process: node2.launch

# GRID MAP PARAMETERS 
grid_map_topic: /ecs/grid_map

grid_map_visualizations:

  - name: temperature
    type: flat_point_cloud
    params:
      layer: temperature
      height: 0.1



