sensors_node:
  input_topic: /sensors
  sensors_topic: /ecs/sensors

ecs_data_acquisition:
  sensors_topic: /ecs/sensors
  trigger_topic: /ecs/trigger
  gridmap_topic: /ecs/map
  sensors:
    - name: temperature_sensor
      method: diffratio
      parameters: { "sensitivity_threshold": 1.4, "min_length": 40 }
      republish: 0
    - name: humidity_sensor
      method: diffratio
      parameters: { "sensitivity_threshold": 1.4, "min_length": 40 }
      republish: 0
    - name: distance_sensor
      method: varratio
      parameters:
        { "sensitivity_threshold": 1.4, "window_length": 40, "var_stable": 0 }
      republish: 0

centrist_descriptor:
  descriptor_service: /ecs/descriptor
  spatial_division: 4
  descriptor_length: 16

ecs_ibec:
  trigger_topic: /ecs/trigger
  camera_topic: /camera/color/image_raw/compressed
  decision_topic: /ecs/decision
  classifier_pkg: ecs
  classifier_file: joblibs/svm_centrist_4_4_16.joblib
  descriptor_service: /ecs/descriptor
  class_mapping:
    "0": indoor
    "1": outdoor

# ECS SWITCHER PARAMETERS
ecs_rba:
  decision_topic: /ecs/decision
  behaviors:
    - name: indoor
      default: 1
      commands:
        - set, decision, indoor
        - set, test_param, 1
    - name: outdoor
      commands:
        - set, decision, outdoor
# GRID MAP PARAMETERS
#grid_map_topic: /ecs/grid_map
#
#grid_map_visualizations:
#  - name: temperature
#    type: flat_point_cloud
#    params:
#      layer: temperature
#      height: 0.1
