# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: ROS SETUP NOETIC
        uses: ros-tooling/setup-ros@v0.1
        with:
            required-ros-distributions: noetic
        id: rosSetup
      - name: ROS PACKAGE BUILD
        uses: ros-tooling/action-ros-ci@v0.1
        with:
            package-name: ecs
            target-ros1-distro: noetic
        id: rosPackageBuild
      - name: RUN TESTS
        run: |
          cd ${{ steps.rosPackageBuild.outputs.ros-workspace-directory-name}}
          source ./devel/setup.bash
          cd src/ecs/ecs/test
          python3 -m cpd_tests.py
          
            
            
            
            
            
            
            
   
